// Decodable sentences for "read it, pick the picture" and silly yes/no questions.
// The first level each one can be read at is computed from its words (see tools/validate.mjs).
export const SENTENCES = [
  // before 'the' and 'a': names and bare words only
  { text: 'Dad sat.', pic: '👨🪑' },
  { text: 'Sam did it!', pic: '🧒🎉' },
  { text: 'Mom sat on Dad!', pic: '👩👨' },
  { text: 'dig, dog, dig!', pic: '🐶⛏️' },
  { text: 'Dad got mad.', pic: '👨😠' },
  // the, a + a m s t f d i n o p g
  { text: 'the dog sat.', pic: '🐶' },
  { text: 'a pig sat on a mat.', pic: '🐷' },
  { text: 'a pig in the fog.', pic: '🐷🌫️' },
  { text: 'Dad got a map.', pic: '🗺️' },
  { text: 'a dog got a pan.', pic: '🐶🍳' },
  // c k
  { text: 'the cat sat on a mat.', pic: '🐱' },
  { text: 'a cat in a cap.', pic: '🐱🧢' },
  { text: 'a kid can dig.', pic: '🧒⛏️' },
  { text: 'the cat can nap.', pic: '🐱😴' },
  { text: 'a dog can pop a can.', pic: '🐶🥫' },
  // h
  { text: 'a cat in a hat.', pic: '🐱👒' },
  { text: 'the pig got hot.', pic: '🐷🥵' },
  { text: 'a dog can hop on a pig.', pic: '🐶🐷' },
  // u
  { text: 'the pup can hug the cat.', pic: '🐶🤗🐱' },
  { text: 'the pig sat in the mud.', pic: '🐷🟫' },
  { text: 'the sun got hot.', pic: '☀️' },
  { text: 'a nut in a cup.', pic: '🥜🥤' },
  { text: 'a pup in a hut.', pic: '🐶🛖' },
  // b
  { text: 'a bug on a bun.', pic: '🐛🍞' },
  { text: 'a big bus.', pic: '🚌' },
  { text: 'the cat got in the bag.', pic: '🐱👜' },
  { text: 'a bat can hang up.', pic: '🦇' },
  // l
  { text: 'a pig on a log.', pic: '🐷🪵' },
  { text: 'a bug on a lid.', pic: '🐛' },
  { text: 'a doll in a tub.', pic: '🪆🛁' },
  // r
  { text: 'a rat on a rug.', pic: '🐀' },
  { text: 'the rat ran and ran.', pic: '🐀🏃' },
  { text: 'a ram can run up a hill.', pic: '🐏⛰️' },
  // e
  { text: 'a hen on a bed.', pic: '🐔🛏️' },
  { text: 'the red hen fed the pup.', pic: '🐔🐶' },
  { text: 'get in bed!', pic: '🛏️' },
  { text: 'a leg on a hen.', pic: '🦵' },
  // I, is, to
  { text: 'the cat is on the bed.', pic: '🐱🛏️' },
  { text: 'I can run.', pic: '🏃' },
  { text: 'the sun is hot.', pic: '☀️🥵' },
  { text: 'I got a pet rat.', pic: '🧒🐀' },
  { text: 'the bell is big.', pic: '🔔' },
  { text: 'I ran to the bus.', pic: '🏃🚌' },
  // w j v
  { text: 'a big wet dog.', pic: '🐶💦' },
  { text: 'a bug in a web.', pic: '🐛🕸️' },
  { text: 'I will win!', pic: '🏆' },
  { text: 'I can jog to the jet.', pic: '✈️' },
  { text: 'the van is big and red.', pic: '🚐' },
  { text: 'the vet got the cat.', pic: '🐱🩺' },
  { text: 'I jog up the hill.', pic: '🏃⛰️' },
  { text: 'a vet can pet a rat.', pic: '🩺🐀' },
  { text: 'a yak in a van.', pic: '🐃🚐' },
  { text: 'the jazz is fun.', pic: '🎷' },
  // y z x qu
  { text: 'yum! a big yam.', pic: '🍠' },
  { text: 'a fox in a box.', pic: '🦊📦' },
  { text: 'the ox is big.', pic: '🐂' },
  { text: 'I can fix the jet.', pic: '🔧' },
  { text: 'yes! I got six!', pic: '6️⃣' },
  // ck sh ch th wh
  { text: 'a duck on a rock.', pic: '🦆🪨' },
  { text: 'the sock is red.', pic: '🧦' },
  { text: 'the pup is sick.', pic: '🐶🤒' },
  { text: 'a fish in a dish.', pic: '🐟' },
  { text: 'the ship is big.', pic: '🚢' },
  { text: 'a chick in a hat.', pic: '🐤👒' },
  { text: 'I am rich!', pic: '🤑' },
  { text: 'the cat is in the bath.', pic: '🐱🛁' },
  { text: 'a fish can not sit on a chick.', pic: '🐟🐤' },
  { text: 'the bath is hot.', pic: '🛁♨️' },
  { text: 'she is in bed.', pic: '👧🛏️' },
  { text: 'we sat in the sun.', pic: '😎☀️' },
  { text: 'a cup of mud.', pic: '🥤🟫' },
  { text: 'he said yes.', pic: '✅' },
  { text: 'when the sun is up, I get up.', pic: '🌅🧒' },
  { text: 'these hats are red.', pic: '👒👒' },
  // ng nk, blends
  { text: 'a king with a ring.', pic: '🤴💍' },
  { text: 'I can sing a song.', pic: '🎤' },
  { text: 'the bell rang and rang.', pic: '🔔🎶' },
  { text: 'a frog on a log.', pic: '🐸🪵' },
  { text: 'the crab can grab.', pic: '🦀' },
  { text: 'stop the truck!', pic: '🚚🛑' },
  { text: 'I can swim.', pic: '🏊' },
  { text: 'a flag on a ship.', pic: '🚩🚢' },
  { text: 'a clock on a brick.', pic: '🕐🧱' },
  { text: 'I got a drum and I can drum.', pic: '🥁' },
  // end blends, plurals, you was has his
  { text: 'ten ants on a plant.', pic: '🐜🪴' },
  { text: 'the frog can jump.', pic: '🐸' },
  { text: 'six eggs in a nest.', pic: '🥚🪺' },
  { text: 'a skunk in a tent!', pic: '🦨⛺' },
  { text: 'the dog has a hat.', pic: '🐶👒' },
  { text: 'his hat was red.', pic: '👒' },
  { text: 'the cats are in a box.', pic: '🐱📦' },
  { text: 'you are the best!', pic: '🥇' },
  // magic e
  { text: 'a snake on a cake!', pic: '🐍🎂' },
  { text: 'I can skate.', pic: '⛸️' },
  { text: 'the whale is big.', pic: '🐋' },
  { text: 'I ride a bike.', pic: '🚲' },
  { text: 'the kite is red and white.', pic: '🪁' },
  { text: 'a dog with a bone.', pic: '🐶🦴' },
  { text: 'a rose on a nose.', pic: '🌹👃' },
  { text: 'go home, pup!', pic: '🏠🐶' },
  { text: 'she can dive.', pic: '🤿' },
  // vowel teams
  { text: 'a bee in a tree.', pic: '🐝🌳' },
  { text: 'I eat a peach.', pic: '🍑' },
  { text: 'the seal can swim in the sea.', pic: '🦭🌊' },
  { text: 'a queen with green jeans.', pic: '👸👖' },
  { text: 'a snail on a train.', pic: '🐌🚆' },
  { text: 'we play in the rain.', pic: '🌧️' },
  { text: 'a goat in a boat.', pic: '🐐🚤' },
  { text: 'the snow is white.', pic: '❄️' },
  { text: 'a fly in the sky.', pic: '🪰' },
  { text: 'the light is bright.', pic: '💡' },
  { text: 'my kite is up high.', pic: '🪁☁️' },
  { text: 'the moon is up at night.', pic: '🌙' },
  { text: 'a goose at the zoo.', pic: '🪿' },
  { text: 'I see a blue boot.', pic: '👢🔵' },
  { text: 'a cook with a book.', pic: '🧑‍🍳📖' },
  { text: 'look at my foot!', pic: '🦶' },
  { text: 'a cow in a house.', pic: '🐮🏠' },
  { text: 'the clown fell down.', pic: '🤡' },
  { text: 'a mouse on a couch.', pic: '🐭🛋️' },
  { text: 'the boy has a toy.', pic: '👦🧸' },
  { text: 'a coin in the soil.', pic: '🪙' },
  // bossy r, aw, all
  { text: 'a shark in the dark.', pic: '🦈' },
  { text: 'the car is red.', pic: '🚗' },
  { text: 'a star in the sky.', pic: '⭐' },
  { text: 'a horse in a storm.', pic: '🐴⛈️' },
  { text: 'corn on a fork.', pic: '🌽🍴' },
  { text: 'a bird on her hat.', pic: '🐦👒' },
  { text: 'the girl has a green shirt.', pic: '👧👕' },
  { text: 'the ball is small.', pic: '⚽' },
  { text: 'I saw a cat yawn.', pic: '🐱🥱' },
  { text: 'the leaf fell in the fall.', pic: '🍂' },
  // tricky words, soft c/g, big words
  { text: 'where is the cat?', pic: '🐱❓' },
  { text: 'they have a big dog.', pic: '🐕' },
  { text: 'what is in the box?', pic: '📦❓' },
  { text: 'a witch with a cat.', pic: '🧙🐱' },
  { text: 'mice eat rice.', pic: '🐭🍚' },
  { text: 'I can catch the ball.', pic: '⚾' },
  { text: 'a chick can hatch.', pic: '🐣' },
  { text: 'a rabbit in a basket.', pic: '🐰🧺' },
  { text: 'the turtle is happy.', pic: '🐢😀' },
  { text: 'a puppy with an apple.', pic: '🐶🍎' },
  { text: 'a rocket in the sky.', pic: '🚀' },
  { text: 'a spider on a pumpkin.', pic: '🕷️🎃' },
  { text: 'the monster had a cupcake.', pic: '👹🧁' },
  { text: 'I love my puppy.', pic: '🐶❤️' },
  { text: 'one duck, two ducks.', pic: '🦆🦆' },
  { text: 'come and see the rainbow!', pic: '🌈' },
  { text: 'put the candle on the cake.', pic: '🕯️🎂' },
  { text: 'the frog jumped in the pond.', pic: '🐸💦' },
  { text: 'the puppy licked my hand.', pic: '🐶✋' },
  { text: 'we played in the snow.', pic: '⛄' },
  { text: 'Dad cooked a big pancake.', pic: '🥞' },
  { text: 'my friend is very kind.', pic: '🤝' },
  { text: 'the water is cold.', pic: '💧🥶' },
  { text: 'my mother and my brother walk to the park.', pic: '👩👦🌳' },
  { text: 'once, a tiger found a very old hat.', pic: '🐯🎩' },
];

export const QUESTIONS = [
  // can
  { text: 'can a pig nap?', yes: true, pic: '🐷' },
  { text: 'can a cap nap?', yes: false, pic: '🧢' },
  { text: 'can a pan dig?', yes: false, pic: '🍳' },
  { text: 'can a dog sit?', yes: true, pic: '🐶' },
  { text: 'can a map sit?', yes: false, pic: '🗺️' },
  { text: 'can a cat nap?', yes: true, pic: '🐱' },
  { text: 'can a hat hop?', yes: false, pic: '👒' },
  { text: 'can a pig hop?', yes: true, pic: '🐷' },
  { text: 'can a sun hug?', yes: false, pic: '☀️' },
  { text: 'can a pup nap?', yes: true, pic: '🐶' },
  { text: 'can a mug hum?', yes: false, pic: '☕' },
  { text: 'can a kid hug a pup?', yes: true, pic: '🧒' },
  { text: 'can a cup hop?', yes: false, pic: '🥤' },
  { text: 'can a nut dig?', yes: false, pic: '🥜' },
  { text: 'can a bus hop?', yes: false, pic: '🚌' },
  { text: 'can a bat nap?', yes: true, pic: '🦇' },
  { text: 'can a big pig fit in a cup?', yes: false, pic: '🐷' },
  { text: 'can a bug hug a bus?', yes: false, pic: '🐛' },
  { text: 'can a log hop?', yes: false, pic: '🪵' },
  { text: 'can a pill hug?', yes: false, pic: '💊' },
  { text: 'can a doll run?', yes: false, pic: '🪆' },
  { text: 'can a rat run?', yes: true, pic: '🐀' },
  { text: 'can a bed run?', yes: false, pic: '🛏️' },
  { text: 'can a pen hop?', yes: false, pic: '🖊️' },
  { text: 'can a hen get fed?', yes: true, pic: '🐔' },
  { text: 'can an egg run?', yes: false, pic: '🥚' },
  // is
  { text: 'is the sun hot?', yes: true, pic: '☀️' },
  { text: 'is a bug big?', yes: false, pic: '🐛' },
  { text: 'is a hat a pet?', yes: false, pic: '👒' },
  { text: 'is a bus big?', yes: true, pic: '🚌' },
  { text: 'is a nut a bug?', yes: false, pic: '🥜' },
  { text: 'is a pig red?', yes: false, pic: '🐷' },
  { text: 'can ten pigs fit in a cup?', yes: false, pic: '🔟' },
  { text: 'is the sun wet?', yes: false, pic: '☀️' },
  { text: 'can a dog wag?', yes: true, pic: '🐶' },
  { text: 'can a web get wet?', yes: true, pic: '🕸️' },
  { text: 'can a jet jog?', yes: false, pic: '✈️' },
  { text: 'can a jug jog?', yes: false, pic: '🫗' },
  { text: 'can a van jog?', yes: false, pic: '🚐' },
  { text: 'can a vet hug a pup?', yes: true, pic: '🩺' },
  { text: 'is a yam a pet?', yes: false, pic: '🍠' },
  { text: 'can a yak yell?', yes: false, pic: '🐃' },
  { text: 'can a fox fit in a box?', yes: true, pic: '🦊' },
  { text: 'can a box run?', yes: false, pic: '📦' },
  { text: 'is an ox big?', yes: true, pic: '🐂' },
  { text: 'can a duck quack?', yes: true, pic: '🦆' },
  { text: 'can a sock quack?', yes: false, pic: '🧦' },
  { text: 'can a rock kick?', yes: false, pic: '🪨' },
  { text: 'can a fish run?', yes: false, pic: '🐟' },
  { text: 'can a ship hop?', yes: false, pic: '🚢' },
  { text: 'is a fish wet?', yes: true, pic: '🐟' },
  { text: 'can a chick chat?', yes: false, pic: '🐤' },
  { text: 'can a chick peck?', yes: true, pic: '🐤' },
  { text: 'is a bath wet?', yes: true, pic: '🛁' },
  { text: 'can a fish be a pet?', yes: true, pic: '🐟' },
  { text: 'can a cat be a hat?', yes: false, pic: '🐱' },
  { text: 'can a chick whack a ship?', yes: false, pic: '🐤' },
  { text: 'can these dogs sing?', yes: false, pic: '🐶🐶' },
  { text: 'can a king sing?', yes: true, pic: '🤴' },
  { text: 'can a ring sing?', yes: false, pic: '💍' },
  { text: 'is a sink wet?', yes: true, pic: '🚰' },
  { text: 'can a frog swim?', yes: true, pic: '🐸' },
  { text: 'can a truck swim?', yes: false, pic: '🚚' },
  { text: 'can a drum swim?', yes: false, pic: '🥁' },
  { text: 'can a brick skip?', yes: false, pic: '🧱' },
  { text: 'can a tent jump?', yes: false, pic: '⛺' },
  { text: 'can a skunk sing?', yes: false, pic: '🦨' },
  { text: 'is milk red?', yes: false, pic: '🥛' },
  { text: 'can a frog jump?', yes: true, pic: '🐸' },
  { text: 'are you a frog?', yes: false, pic: '🐸' },
  { text: 'are ants big?', yes: false, pic: '🐜' },
  { text: 'is his hat a pet?', yes: false, pic: '👒' },
  { text: 'can a snake skate?', yes: false, pic: '🐍' },
  { text: 'is a whale big?', yes: true, pic: '🐋' },
  { text: 'can a grape wave?', yes: false, pic: '🍇' },
  { text: 'can a cake bake a cake?', yes: false, pic: '🎂' },
  { text: 'can a kite ride a bike?', yes: false, pic: '🪁' },
  { text: 'can a bike smile?', yes: false, pic: '🚲' },
  { text: 'can a bone run?', yes: false, pic: '🦴' },
  { text: 'is a rose red?', yes: true, pic: '🌹' },
  { text: 'can a nose smell?', yes: true, pic: '👃' },
  { text: 'can a bee sting?', yes: true, pic: '🐝' },
  { text: 'can a tree eat?', yes: false, pic: '🌳' },
  { text: 'is the sea wet?', yes: true, pic: '🌊' },
  { text: 'can a sheep read?', yes: false, pic: '🐑' },
  { text: 'is rain wet?', yes: true, pic: '🌧️' },
  { text: 'can a snail paint?', yes: false, pic: '🐌' },
  { text: 'can a goat row a boat?', yes: false, pic: '🐐' },
  { text: 'is snow hot?', yes: false, pic: '❄️' },
  { text: 'can soap eat toast?', yes: false, pic: '🧼' },
  { text: 'can a goat fly?', yes: false, pic: '🐐' },
  { text: 'can a bee fly?', yes: true, pic: '🐝' },
  { text: 'is the sky green?', yes: false, pic: '🌌' },
  { text: 'is the moon blue?', yes: false, pic: '🌙' },
  { text: 'can a spoon eat food?', yes: false, pic: '🥄' },
  { text: 'can a goose swim?', yes: true, pic: '🪿' },
  { text: 'can a book cook?', yes: false, pic: '📖' },
  { text: 'can a cow say moo?', yes: true, pic: '🐮' },
  { text: 'can a mouse eat a house?', yes: false, pic: '🐭' },
  { text: 'can an owl fly?', yes: true, pic: '🦉' },
  { text: 'is a cloud loud?', yes: false, pic: '☁️' },
  { text: 'is a coin a toy?', yes: false, pic: '🪙' },
  { text: 'can a boy jump?', yes: true, pic: '👦' },
  { text: 'can a car swim?', yes: false, pic: '🚗' },
  { text: 'can a shark bark?', yes: false, pic: '🦈' },
  { text: 'can a horse eat corn?', yes: true, pic: '🐴' },
  { text: 'can a fork snore?', yes: false, pic: '🍴' },
  { text: 'can a bird chirp?', yes: true, pic: '🐦' },
  { text: 'can a shirt surf?', yes: false, pic: '👕' },
  { text: 'can a ball yawn?', yes: false, pic: '⚽' },
  { text: 'can a cat crawl?', yes: true, pic: '🐱' },
  { text: 'do fish swim?', yes: true, pic: '🐟' },
  { text: 'do pigs fly?', yes: false, pic: '🐷' },
  { text: 'do cars have legs?', yes: false, pic: '🚗' },
  { text: 'do you have a nose?', yes: true, pic: '👃' },
  { text: 'is ice hot?', yes: false, pic: '🧊' },
  { text: 'can a dog fetch?', yes: true, pic: '🐶' },
  { text: 'is a gem a snack?', yes: false, pic: '💎' },
  { text: 'can a rabbit hop?', yes: true, pic: '🐰' },
  { text: 'can a pumpkin sing?', yes: false, pic: '🎃' },
  { text: 'is a candle hot?', yes: true, pic: '🕯️' },
  { text: 'can a rocket fly?', yes: true, pic: '🚀' },
  { text: 'can a turtle ride a bike?', yes: false, pic: '🐢' },
  { text: 'could a whale fit in a cup?', yes: false, pic: '🐋' },
  { text: 'would a cat like a fish?', yes: true, pic: '🐱' },
  { text: 'do you have two hands?', yes: true, pic: '✋' },
  { text: 'if a cat jumped in a pond, would it get wet?', yes: true, pic: '🐱' },
  { text: 'can a zip yell?', yes: false, pic: '🤐' },
  { text: 'can these hats run?', yes: false, pic: '👒👒' },
  { text: 'can a snowman go swimming?', yes: false, pic: '⛄' },
  { text: 'is a crying baby happy?', yes: false, pic: '👶' },
  { text: 'if you dropped an egg, would it crack?', yes: true, pic: '🥚' },
  { text: 'if a dog barked, would it be loud?', yes: true, pic: '🐶' },
  { text: 'does a fish walk?', yes: false, pic: '🐟' },
  { text: 'does a dog talk?', yes: false, pic: '🐶' },
  { text: 'can you walk on water?', yes: false, pic: '💧' },
  { text: 'does a duck like water?', yes: true, pic: '🦆' },
];
